
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Oct 26 23:12:47 CST 2019
//----------------------------------------------------

package AnalizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_de_cierre = 83;
  public static final int AS = 28;
  public static final int REAL = 42;
  public static final int COLLATE = 21;
  public static final int COLUMN = 24;
  public static final int TIME = 43;
  public static final int TIMESTAMP = 44;
  public static final int Igualdad = 71;
  public static final int GO = 10;
  public static final int Menor = 66;
  public static final int Coma = 77;
  public static final int TABLE = 9;
  public static final int Porcentaje = 65;
  public static final int Punto = 78;
  public static final int NAME = 23;
  public static final int BLOB = 31;
  public static final int YEAR = 40;
  public static final int Corchete_de_apertura = 79;
  public static final int Mayor_o_igual = 69;
  public static final int ALL = 27;
  public static final int Resta = 62;
  public static final int INTEGER = 35;
  public static final int Int = 3;
  public static final int DOUBLE = 49;
  public static final int Bit = 5;
  public static final int NOT = 26;
  public static final int Suma = 61;
  public static final int Llaves = 87;
  public static final int VIEW = 14;
  public static final int TEXT = 46;
  public static final int FLOAT = 36;
  public static final int IMAGE = 41;
  public static final int String = 6;
  public static final int SMALLINT = 33;
  public static final int Error_Comentario_Sin_Cerrar = 91;
  public static final int Corchete_de_cierre = 80;
  public static final int ALTER = 19;
  public static final int LONG = 48;
  public static final int INDEX = 13;
  public static final int EXISTS = 17;
  public static final int CLUSTERED = 58;
  public static final int CHAR = 29;
  public static final int BOOLEAN = 38;
  public static final int NONCLUSTERED = 59;
  public static final int Punto_y_coma = 76;
  public static final int ADD = 52;
  public static final int MAX = 51;
  public static final int Numeral = 89;
  public static final int Or = 74;
  public static final int And = 73;
  public static final int INT = 34;
  public static final int Mayor = 68;
  public static final int Error_Caracter_Invalido = 93;
  public static final int Error_Cadena_Invalida = 92;
  public static final int BIT = 32;
  public static final int NULL = 25;
  public static final int EOF = 0;
  public static final int Parentesis = 84;
  public static final int Corchetes = 81;
  public static final int Llave_de_apertura = 85;
  public static final int Division = 64;
  public static final int Parentesis_de_apertura = 82;
  public static final int UNIQUE = 57;
  public static final int DATE = 39;
  public static final int MODIFY = 22;
  public static final int error = 1;
  public static final int ON = 18;
  public static final int Diferente = 72;
  public static final int CURRENT = 20;
  public static final int IF = 16;
  public static final int CURSOR = 45;
  public static final int Float = 4;
  public static final int IDENTITY = 56;
  public static final int Arroba = 88;
  public static final int NCHAR = 50;
  public static final int DATABASE = 12;
  public static final int TRUNCATE = 8;
  public static final int BINARY = 30;
  public static final int Identificador = 2;
  public static final int Menor_o_igual = 67;
  public static final int VARCHAR = 37;
  public static final int Digito = 7;
  public static final int FOREIGN = 60;
  public static final int Not = 75;
  public static final int PRIMARY = 54;
  public static final int BYTE = 47;
  public static final int Llave_de_cierre = 86;
  public static final int Igual = 70;
  public static final int DROP = 11;
  public static final int KEY = 55;
  public static final int CONSTRAINT = 53;
  public static final int Multiplicacion = 63;
  public static final int USER = 15;
  public static final int Doble_numeral = 90;
}

