
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 13 18:18:44 CST 2019
//----------------------------------------------------

package AnalizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 23;
  public static final int Corchetes = 30;
  public static final int Corchete_de_cierre = 29;
  public static final int Punto_y_coma = 25;
  public static final int Coma = 26;
  public static final int Error_Caracter_Invalido = 42;
  public static final int TRUNCATE = 7;
  public static final int Parentesis_de_cierre = 32;
  public static final int Diferente = 21;
  public static final int Numeral = 38;
  public static final int Menor = 15;
  public static final int Arroba = 37;
  public static final int Mayor = 17;
  public static final int Error_Comentario_Sin_Cerrar = 40;
  public static final int Parentesis_de_apertura = 31;
  public static final int Punto = 27;
  public static final int Division = 13;
  public static final int Int = 3;
  public static final int Doble_numeral = 39;
  public static final int Float = 4;
  public static final int EOF = 0;
  public static final int Not = 24;
  public static final int TABLE = 8;
  public static final int And = 22;
  public static final int error = 1;
  public static final int Error_Cadena_Invalida = 41;
  public static final int Corchete_de_apertura = 28;
  public static final int Mayor_o_igual = 18;
  public static final int Llaves = 36;
  public static final int Llave_de_cierre = 35;
  public static final int String = 6;
  public static final int Parentesis = 33;
  public static final int Identificador = 2;
  public static final int Llave_de_apertura = 34;
  public static final int Resta = 11;
  public static final int Porcentaje = 14;
  public static final int Igualdad = 20;
  public static final int Bit = 5;
  public static final int Multiplicacion = 12;
  public static final int Suma = 10;
  public static final int Igual = 19;
  public static final int Menor_o_igual = 16;
  public static final int GO = 9;
}

